### ISSUE TITLE
Terminal vs. Terminator issue

### ISSUE THREAD

**Issue by PetrSvirak** [LindaLangerova/Furfur#10]
This one is a bit complex scenario, but happened to at least 2 people I know of:

*Given* I fight the Terminator
*And* I acquire one or two `characters`
*And* I don't read the terminal messages (just press `X`)
*And* I throw a `character` immediately (just press `C`)
*And* I don't use any other tactic (just repeat)

*When* Terminator dies
*And* I automatically acquire another `character`

*Then* I completely miss what Terminator says

It would be great if terminal turned itself off after a certain number of characters - either "shoot & hit N times in a row or jump off the platform and repeat" or "shoot & hit last M times or repeat" strategy seems tempting to me. The former seems a bit more old-school (in a good way) just like `C` is 😼

**Comment by LindaLangerova** [comment]
![cookieissue](https://user-images.githubusercontent.com/33051533/40282394-edfc9336-5c6e-11e8-93f4-644c036a4e3a.png)
