### ISSUE TITLE
Terminator does not starting moving after the first hit

### ISSUE THREAD

**Issue by PetrSvirak** [LindaLangerova/Furfur#23]
Bug or cheat (or feature)?

**Comment by LindaLangerova** [comment]
He starts to move not by being hit, but when furfur's close enough... Maybe I will make bullets disappear earlier. But you have a point, thanks :)

**Comment by LindaLangerova** [comment]
![cookieissue](https://user-images.githubusercontent.com/33051533/40282068-9cfe4f92-5c69-11e8-81b1-c8076526eeff.png)
