### ISSUE TITLE
On the way to the Terminator for the first time

### ISSUE THREAD

**Issue by PetrSvirak** [LindaLangerova/Furfur#9]
It is a bit counterintuitive being required to press `X` once more after the ancient key is inserted. It would be great if `FurFur` got through automatically after inserting the key.

**Comment by LindaLangerova** [comment]
![cookieissue](https://user-images.githubusercontent.com/33051533/40282262-f134e0a0-5c6c-11e8-9e61-680b79fc0fa2.png)
